Map<String, String> uuidMap = {
  "1800": "Generic Access service",
  "1801": "Generic Attribute service",
  "1802": "Immediate Alert service",
  "1803": "Link Loss service",
  "1804": "Tx Power service",
  "1805": "Current Time service",
  "1806": "Reference Time Update service",
  "1807": "Next DST Change service",
  "1808": "Glucose service",
  "1809": "Health Thermometer service",
  "180A": "Device Information service",
  "180D": "Heart Rate service",
  "180E": "Phone Alert Status service",
  "180F": "Battery service",
  "1810": "Blood Pressure service",
  "1811": "Alert Notification service",
  "1812": "Human Interface Device service",
  "1813": "Scan Parameters service",
  "1814": "Running Speed and Cadence service",
  "1815": "Automation IO service",
  "1816": "Cycling Speed and Cadence service",
  "1818": "Cycling Power service",
  "1819": "Location and Navigation service",
  "181A": "Environmental Sensing service",
  "181B": "Body Composition service",
  "181C": "User Data service",
  "181D": "Weight Scale service",
  "181E": "Bond Management service",
  "181F": "Continuous Glucose Monitoring service",
  "1820": "Internet Protocol Support service",
  "1821": "Indoor Positioning service",
  "1822": "Pulse Oximeter service",
};
